using PixelPuzzle.Utility;

namespace PixelPuzzle.Logic {
    public class Level : NotifyPropertyChangedBase {
        private bool isComplete;

        public bool IsAutoGenerated { get; }
        public int LevelNumber { get; }
        public Difficulty Difficulty { get; }
        public int[,] Map { get; }
        public CellValue[,] UserMap { get; set; }
        public bool IsComplete {
            get { return isComplete; }
            set {
                if (isComplete != value) {
                    isComplete = value;
                    OnPropertyChanged(nameof(IsComplete));
                }
            }
        }

        public string Key => $"{Difficulty}.{LevelNumber}";

        public Level(int levelNumber, Difficulty difficulty, int[,] map, bool isAutoGenerated = false) {
            LevelNumber = levelNumber;
            Difficulty = difficulty;
            Map = map;
            IsAutoGenerated = isAutoGenerated;
        }
    }
}
